# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js publish package

on:
    push:
        tags: [core@v*, objection@v*]
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Build core
        run: npx lerna run build --scope "@knestjs/core"
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Build @knestjs/core
        run: npx lerna run build --scope "@knestjs/core"

      - run: npm publish ./packages/core --access public
        if: contains(github.ref, 'core@v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build @knestjs/objection
        if: contains(github.ref, 'objection@v')
        run: npx lerna run build --scope "@knestjs/objection"
      
      - run: npm publish ./packages/objection --access public
        if: contains(github.ref, 'objection@v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
