# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build @knestjs/core
      run: npx lerna run build --scope "@knestjs/core"
    - name: Build @knestjs/objection
      run: npx lerna run build --scope "@knestjs/objection"
    - name: Run tests
      run: npm run test:cov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      # Seems there is slightly differences in the coverage of both versions
      if: matrix.node-version == '16.x'
